baseURL = "https://rme.example/"
title = "Rowboat Music Example"

theme = "rowboat-music"

paginate = 2

[params]
recentReleaseCount = 2

[params.refs.wips]
title = "WIPs"
occurrenceFormat = "(WIP of %s)"
